server:
  port: 8000  # 网关端口，用户访问这个端口
  tomcat:
    threads:
      max: 8  # 最大线程数，默认200，改成800
      min-spare: 2  # 最小空闲线程数
spring:
  application:
    name: shortlink-gateway  # 网关在 Nacos 里的服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 你的 Nacos 服务端口（不是控制台 8080）
    gateway:
      routes:
        # 路由到 shortlink-admin 服务
        - id: shortlink-admin
          uri: lb://shortlink-admin  # lb:// 代表负载均衡，从 Nacos 找服务
          predicates:
            - Path=/api/short-link/admin/**  # 匹配 admin 接口路径
          filters:
#            - StripPrefix=1  # 去掉 /api 前缀，转发给 admin 时变成 /short-link/admin/**

        # 路由到 shortlink-project 服务（核心短链接服务）
        - id: shortlink-project
          uri: lb://shortlink-project
          predicates:
            - Path=/api/short-link/project/**
#          filters:
#            - StripPrefix=1
    # Sentinel 核心配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858 # Sentinel 控制台地址
        port: 8719 # 客户端和控制台通信端口（默认8719，冲突可改）
      eager: true # 启动时主动连接控制台（避免首次请求才初始化）
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      # 2核4G服务器Redis连接池配置（Lettuce）
      lettuce:
        pool:
          max-active: 12          # 最大连接数：Tomcat线程数+4=12
          max-idle: 8             # 最大空闲连接：8
          min-idle: 2             # 最小空闲连接：2
          max-wait: 3000ms        # 连接等待超时：3秒