server:
  port: 8000  # 网关端口，用户访问这个端口

spring:
  application:
    name: shortlink-gateway  # 网关在 Nacos 里的服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849  # 你的 Nacos 服务端口（不是控制台 8080）
    gateway:
      routes:
        # 路由到 shortlink-admin 服务（你截图里的 admin 服务）
        - id: shortlink-admin
          uri: lb://shortlink-admin  # lb:// 代表负载均衡，从 Nacos 找服务
          predicates:
            - Path=/api/short-link/admin/**  # 匹配 admin 接口路径
          filters:
#            - StripPrefix=1  # 去掉 /api 前缀，转发给 admin 时变成 /short-link/admin/**

        # 路由到 shortlink-project 服务（核心短链接服务）
        - id: shortlink-project
          uri: lb://shortlink-project
          predicates:
            - Path=/api/short-link/project/**
#          filters:
#            - StripPrefix=1
    # Sentinel 核心配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:8081 # Sentinel 控制台地址
        port: 8719 # 客户端和控制台通信端口（默认8719，冲突可改）
      eager: true # 启动时主动连接控制台（避免首次请求才初始化）
  data:
    redis:
      host: 192.168.100.152
      port: 6379
      password: 123456
      database: 0