server:
  port: 8001

spring:
  application:
    name: shortlink-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  data:
    redis:
      host: 192.168.100.152
      port: 6379
      password: 123456
      database: 0
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  protocol: http
  domain:
    default: nurl.ink