server:
  port: 8001
  tomcat:
    threads:
      max: 200  # 最大线程数，默认200，改成800
      min-spare: 50  # 最小空闲线程数
spring:
  application:
    name: shortlink-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 40
      minimum-idle: 20
      idle-timeout: 500
      connection-timeout: 30000
      max-lifetime: 1800000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  protocol: http
  domain:
    default: nurl.local
gaode:
  amap:
    key: c2a69289fa819a2e36b6e467c82d692c
# RocketMQ 核心配置
rocketmq:
  name-server: 127.0.0.1:9876  # 虚拟机 NameServer 地址（关键！）
  producer:
    group: default-producer-group  # 生产者组名，自定义
    send-message-timeout: 3000  # 发送超时时间
    retry-times-when-send-failed: 2  # 发送失败重试次数
  consumer:
    group: default-consumer-group  # 消费者组名，自定义
    enable-msg-trace: true

